name: ai_voice_to_hand_signs_project
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  # Utilities
  # Icons
  cupertino_icons: ^1.0.8
  iconsax_flutter: ^1.0.1
  google_fonts: ^8.0.0

  # Google Firebase
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  firebase_database: ^12.1.3
  firebase_storage: ^13.0.6
  cloud_functions: ^6.0.6
  firebase_app_check: ^0.4.1+4
  google_sign_in: ^7.2.0
  permission_handler: ^12.0.1
  
  # Logging
  logger: ^2.5.0

  # State Management
  get: ^4.6.6
  audioplayers: ^6.5.1
  record: ^6.2.0
  path_provider: ^2.1.5
  path: ^1.9.1
  video_player: ^2.11.0

  # tflite_flutter: ^0.11.0
  # camera: ^0.11.0+2
  # google_mlkit_commons: ^0.6.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # ------ Local Assets ------
  assets:
    - assets/images/
    - assets/icons/
    - assets/label_map.json

  # ---------------- Local Fonts ----------------
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
